### PR TITLE
template variables

### PR DESCRIPTION
**Pull request by AakashGfude**
template variables missing in conf and adjustment to variables in Makefile

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude genius.

**Comment by mmcky** [comment]
@AakashGfude I see we had two previous commits to address this. Are they both contained in this PR? Can I close the other two?

**Comment by AakashGfude** [comment]
@mmcky we can close this PR :- https://github.com/QuantEcon/python_lecture_sandpit/pull/42

**Comment by mmcky** [comment]
thanks -- done

**Pull request merged**
