### PR TITLE
ENH: Adjust to be compatible with `jupinx`

### PR DESCRIPTION
**Pull request by mmcky**
This PR:

1. updates the repository to be compatible with `jupinx` utility. It also standardises the UX across `lecture-source-py` and `sandpit` through the Makefile. 
1. enables viewing lectures in `html` by including the `theme` so `jupinx -w --view=website` is enabled. This is quick to execute due to the small number of lectures. 

**Note:** the preview makefile had a `make view` that was a synonym for `make preview`.  Given `jupinx` has `-v, --view` I didn't think the makefile needed this option. 

The `sandpit` can be build either using `make <command>` or using `jupinx`.

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac would you mind checking out this branch if you get the chance and give `jupinx` and/or `make` a test run.

**Comment by mmcky** [comment]
I have done some tests and is working well on my machine you can run:

1. `jupinx -n` for `notebooks`, `jupinx -nv`
1. `jupinx -w --view=website` for `html`

and `make notebooks` and `make website` also work.

**Comment by AakashGfude** [comment]
@mmcky  It is working well on my machine as well. Good to go from my side.

**Comment by mmcky** [comment]
thanks @AakashGfude appreciate the check.

@jstac this PR should be good to go if you wanted to check it out and see if your workflows are constant and work well.

**Pull request merged**
