### PR TITLE
new lecture added to sandpit  'markov_jump_lq_control.rst'

### PR DESCRIPTION
**Pull request by AnjuJoon**

### CODE REVIEW

**Comment by AnjuJoon** [comment]
@jstac what should be the name of this lecture, title and subtitle?

**Comment by jstac** [comment]
Hi @AnjuJoon , can you please remove the ipynb_checkpoints file (see the list of changed files).

If possible, please fix the merge conflict at the same time.

Have you generated the notebook and compared it with the original one?

For the file name, let's have `markov_jump_lq_control`.  For the title, please use "Markov Jump LQ Control".  Don't worry about the rest for now --- it's still a work in progress.

Thanks.

**Comment by AnjuJoon** [comment]
@jstac I have made all said changes in the lecture. I will keep working on this. It is ready to merge in master now.

**Comment by jstac** [comment]
Thanks Anju.

**Pull request merged**
