### PR TITLE
Add the lecture of Coase's theory of the firm.

### PR DESCRIPTION
**Pull request by jstac**

### CODE REVIEW

**Comment by AnjuJoon** [comment]
@jstac I have committed some changes. Please have a look at them and let me know if more changes are needed
Also, I was not so sure about inserting Unicode characters in code so please let me know if it is to be done.

**Comment by jstac** [comment]
Great work, Anju!  Thank you.

**Comment by mmcky** [comment]
Thanks. I’ll build this latest master this afternoon.

**Comment by mmcky** [comment]
ah - I thought this was in the `lecture-source-py` repository.

**Pull request merged**
